# Project Information
site_name: Coolcrasher TechDocs
pages:
    - Home: index.md
    - Mkdocs: guideMkdocs.md
    - Git: guideGit.md
    - Quick Links: impLinks.md


# Configuration 
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo:
    icon: 'description'
    
markdown_extensions:
  - toc:
      permalink: true
      
  